### PR TITLE
Add config option to omit colophon.

### PR DESCRIPTION
**Pull request by frankduncan**
Needed for one of the generation projects related to torque, because
having the colophon on the pages was confusing search results and we
wanted the generated pages to truly be blank.

### CODE REVIEW

**Review by kfogel — COMMENTED** [review]
I would have expected the `omit_colophon` config parameter to propagate through and affect the value of the `include_colophon` argument to `_save_page()`, instead of being tested in addition to that argument.

Is there a reason not to do it that way?

**Comment by frankduncan** [comment]
@kfogel It might be right to just remove include_colophon and only do omit_colophon.  The reason we had it was we were adding helper pages that were mediawiki templates that were partials.  So that meant that the colophon was showing up on the page twice (once from the mediawiki template, and once from the generated actual page).  We now use the templating system for this kind of in depth work, and so this distinction is not really useful anymore.  The code would be simpler to just remove it since I don't think there's a philosophical need and the practical need was really just an artifact of how I was abusing csv2wiki.

**Comment by kfogel** [comment]
That makes sense.  That sounds like two distinct changes: one to remove "include_colophon", and then a second one to add "omit_colophon" (i.e., the latter change would be basically this PR, but rebased to be after the removal of "include_colophon").  Am I on the right track?

**Comment by kfogel** [comment]
LGTM!  Thanks for the clean division into two commits.

**Pull request merged**
